export const ANALYTICS_EVENTS = {
  PAGE_VIEWED: "page_viewed",
  SIGNUP_STARTED: "signup_started",
  SIGNUP_CREATED: "signup_created",
  LOGIN_COMPLETED_UI: "login_completed_ui",
  LOGOUT_CLICKED: "logout_clicked",
  PLANS_VIEWED: "plans_viewed",
  UPGRADE_CTA_CLICKED: "upgrade_cta_clicked",
  CHECKOUT_STARTED: "checkout_started",
  CHECKOUT_SUCCESS_SCREEN_VIEWED: "checkout_success_screen_viewed",
  ONBOARDING_STARTED: "onboarding_started",
  ONBOARDING_COMPLETED_UI: "onboarding_completed_ui",
  PASSWORD_RESET_REQUESTED: "password_reset_requested",
  PASSWORD_RESET_COMPLETED_UI: "password_reset_completed_ui",
  TERMS_ACCEPTED_UI: "terms_accepted_ui",
  PROFILE_UPDATED_UI: "profile_updated_ui",
  PASSWORD_CHANGED_UI: "password_changed_ui",
  PLAN_GATE_BLOCKED: "plan_gate_blocked",
  MODAL_OPENED: "modal_opened",
  UI_ERROR_VIEWED: "ui_error_viewed",
} as const;
