import { ANALYTICS_EVENTS } from "@/lib/analytics/events";

export const CALENDAR_ANALYTICS_EVENTS = {
  VIEWED: ANALYTICS_EVENTS.CALENDAR_VIEWED,
  CREATE_CLICKED: ANALYTICS_EVENTS.CALENDAR_CREATE_CLICKED,
  AI_CLICKED: ANALYTICS_EVENTS.CALENDAR_AI_CLICKED,
  TUTORIAL_STARTED: ANALYTICS_EVENTS.CALENDAR_TUTORIAL_STARTED,
  TUTORIAL_COMPLETED: ANALYTICS_EVENTS.CALENDAR_TUTORIAL_COMPLETED,
  TUTORIAL_SKIPPED: ANALYTICS_EVENTS.CALENDAR_TUTORIAL_SKIPPED,
  TUTORIAL_REOPENED: ANALYTICS_EVENTS.CALENDAR_TUTORIAL_REOPENED,

  VIEW_CHANGED: "calendar_view_changed",
  DATE_NAVIGATED: "calendar_date_navigated",
  ITEM_OPENED: "calendar_item_opened",
  ITEM_CREATED: "calendar_item_created",
  ITEM_UPDATED: "calendar_item_updated",
  ITEM_DELETED: "calendar_item_deleted",
  DAY_MODAL_OPENED: "calendar_day_modal_opened",
  AI_SUGGESTION_REQUESTED: "calendar_ai_suggestion_requested",
  AI_BLOCKED_BY_LIMIT: "calendar_ai_blocked_by_limit",
} as const;
